Add initial PURE 1 based on TAP 1
uptane/pures pull request #1
Opened 2021-07-09 18:42 UTC by mnm678

This document is very similar to TAP 1. A couple of changes that we may want to discuss include:

* **Who is the final decision maker for PUREs?** TUF has a small group of TAP editors, with Justin Cappos as the consensus builder. In this draft of PURE 1 I put the Uptane Steering Committee as the final decision makers, but other suggestions are welcome.
* **Do PUREs need a reference implementation?** As Uptane does not have a formal reference implementation, I removed this requirement. However, it may still be valuable to require some kind of working code before making larger changes to the Uptane Standard.

2021-07-14 08:54 UTC, tkfu approved these changes
I think this is all quite sensible, and I'd support moving this to Accepted status ASAP, with an eye to making it Final at the next standards committee meeting.

2021-07-14 10:39 UTC, pattivacek approved these changes

2021-07-19 19:12 UTC, jhdalek55 requested changes
I suggested a few changes that I think simplify or clarify the language,

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +PURE stands for Proposed Uptane Revision and Enhancement and is largely modeled after a similar type of document used by The Update Framework (TUF)'s TUF Augmentation Proposal (TAP) process.  A PURE
I'm proposing a few changes to the opening paragraph

PURE stands for Proposed Uptane Revision and Enhancement and offers a formal method for members of the community to propose the addition or modification of the Uptane specification. Both the method and the document format is largely modeled on the TUF Augmentation Proposal (TAP) used by The Update Framework (TUF). A PURE is a design document that describes a new feature for Uptane or for its processes or environment. Every PURE should provide both a concise technical specification of the feature and a rationale for the feature's inclusion.

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +The status of a PURE indicates its progress through the development process. The different status classifications are defined below. Unless otherwise specified, each status applies to both kinds of P
Are there different kinds of PUREs?

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +* **Deferred** PUREs are potentially good ideas which are not being actively developed, or where progress is not being made.
* **Deferred** PUREs are potentially good ideas that are not being actively developed at this moment, or where progress is not being made.

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +* A **Rejected** PURE is one which the Uptane Steering Committee have decided is ultimately not a good idea.
* A **Rejected** PURE is one which the Uptane Steering Committee has decided is not ultimately a good idea.

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +* **Withdrawn** PUREs are submissions which the champion, or lead author, of the PURE has decided are no longer worth pursuing.
* **Withdrawn** PUREs are submissions removed from consideration because their champions, or lead authors,  have decided they are no longer worth pursuing.

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +Each PURE MUST have a champion -- someone who writes the PURE using the style and format described below, shepherds the discussions in the appropriate forums, and attempts to build community consensu
"PURE-able" reads a bit odd and its meaning is really unclear. Perhaps change to "...should first attempt to ascertain whether the idea is feasible and beneficial to the Standard."

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +Once a submission is approved for inclusion in the PURE repository, the repository maintainers will assign it a number, mark its status as "Draft", and merge the initial draft.  The maintainers will
Parallel structure problems:
Reasons for denying a PURE at this stage include a fundamentally unsound technology base, duplication of effort, weak or insufficient motivation, backwards compatibility issues, or a submission that is simply not in keeping with the Uptane philosophy.

2021-07-19 19:12 UTC, jhdalek55 commented on pure1.md
> +3. *Motivation* -- The motivation is critical for PUREs that want to change Uptane. It should clearly explain why the existing standard is inadequate to address the problem that the PURE solves. It s
3. *Motivation* -- Any proposal seeking to change Uptane requires a strong and compelling motivation.

2021-07-19 20:04 UTC, mnm678 commented
Thanks @jhdalek55. I updated the pr based on your feedback

2021-07-19 20:07 UTC, jhdalek55 approved these changes
Looks good to me. Thanks.

2021-09-08 15:30 UTC, trishankatdatadog approved these changes

2021-09-08 15:31 UTC, merged

2021-09-08 15:40 UTC, jhdalek55 commented
@tkfu @pattivacek @justincappos Is there any further discussion needed? If not I am going to merge this.

2021-09-08 15:49 UTC, jhdalek55 commented
@mnm678 To answer the questions posed above, I agree that there should a group who have the final say. I'm fine with it being our Steering Committee @justincappos @iramcdonald @weimerskirchandre. I leave the reference implementation question to others. It makes some sense to try out an idea before advocating for a change in the Standard, but I don't feel qualified to advocate for it.

2021-09-08 16:04 UTC, trishankatdatadog commented
We have merged the PURE as it is now, but we can always make changes later as needed.

2021-09-08 16:08 UTC, jhdalek55 commented
Yeah. This is fine. The two issues mentioned above do not not need to be resolved in this initial posting.